// <auto-generated />
using System;
using EventService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250618030741_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventService.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1e2f3a4b5c6d"),
                            Category = "Music",
                            Description = "Experience the biggest outdoor music event of the year.",
                            EventDateTime = new DateTime(2025, 7, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1501238295340-c810d3c156d2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHN1bW1lciUyMGZlc3RpdmFsfGVufDB8fDB8fHww",
                            Location = "Central Park, NY",
                            Price = 120,
                            Title = "Summer Music Festival"
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-f1a2-4b3c-9d8e-7f6a5b4c3d2e"),
                            Category = "Technology",
                            Description = "Explore the future of technology with global innovators.",
                            EventDateTime = new DateTime(2025, 9, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1655963858503-1db062739349?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRlY2glMjBleHBvfGVufDB8fDB8fHww",
                            Location = "Silicon Valley, CA",
                            Price = 250,
                            Title = "Tech Expo 2025"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-4c5d-9e8f-7a6b5c4d3e2f"),
                            Category = "Art",
                            Description = "An elegant evening of painting and fine wines.",
                            EventDateTime = new DateTime(2025, 8, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1743043627539-7e9c5a87b789?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGFydCUyMHdpbmUlMjBuaWdodHxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "Downtown LA, CA",
                            Price = 75,
                            Title = "Art & Wine Night"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Category = "Business",
                            Description = "Watch upcoming startups pitch their ideas to investors.",
                            EventDateTime = new DateTime(2025, 10, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3RhcnR1cHxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "Seattle, WA",
                            Price = 40,
                            Title = "Startup Pitch Night"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-4e9f-8a0b-1c2d3e4f5a6b"),
                            Category = "Sports",
                            Description = "Join the community in our annual fitness challenge.",
                            EventDateTime = new DateTime(2025, 6, 2, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFyYXRob258ZW58MHx8MHx8fDA%3D",
                            Location = "Boston, MA",
                            Price = 30,
                            Title = "Marathon 10K Run"
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-d9e0-4f1a-8b2c-3d4e5f6a7b8c"),
                            Category = "Food",
                            Description = "Learn gourmet recipes from a celebrity chef.",
                            EventDateTime = new DateTime(2025, 11, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1683624328172-88fb24625ec1?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y29va2luZyUyMGNsYXNzfGVufDB8fDB8fHww",
                            Location = "Chicago, IL",
                            Price = 100,
                            Title = "Cooking Masterclass"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4a3b-9c8d-7e6f5a4b3c2d"),
                            Category = "Photography",
                            Description = "Master camera techniques and visual storytelling.",
                            EventDateTime = new DateTime(2025, 9, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1486892539609-d5322f938c50?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGhvdG9ncmFwaHklMjB3b3Jrc2hvcHxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "Denver, CO",
                            Price = 60,
                            Title = "Photography Workshop"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Category = "Film",
                            Description = "Watch and discuss short films from new directors.",
                            EventDateTime = new DateTime(2025, 8, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1627126053538-5eefab972223?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aW5kaWUlMjB0aGVhdGVyfGVufDB8fDB8fHww",
                            Location = "Brooklyn, NY",
                            Price = 20,
                            Title = "Indie Film Screening"
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-a8b9-4c0d-9e1f-2a3b4c5d6e7f"),
                            Category = "Gaming",
                            Description = "Bring your rig and game all night long.",
                            EventDateTime = new DateTime(2025, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1633545491399-54a16aa6a871?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bGFufGVufDB8fDB8fHww",
                            Location = "Austin, TX",
                            Price = 50,
                            Title = "Gaming LAN Party"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-4d2e-9f3a-4b5c6d7e8f9a"),
                            Category = "Music",
                            Description = "Smooth jazz music with drinks and vibes.",
                            EventDateTime = new DateTime(2025, 7, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8amF6enxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "New Orleans, LA",
                            Price = 45,
                            Title = "Jazz Night Live"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
